on:
  workflow_dispatch:

name: Build PJRT

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    name: Build PJRT
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          git clone https://github.com/openxla/xla
          cd xla
          git checkout 6319f0d

      - run: |
          choco install llvm --params "'/InstallDir=C:\llvm'" -y
          which clang
          clang --version

      - run: |
          cd xla
          python configure.py --backend=cpu --os=windows --host_compiler=clang --clang_path=C:/PROGRA~1/LLVM/bin/clang.exe
          cat xla_configure.bazelrc

      - run: |
          cd xla
          bazel build --config=clang_local //xla/pjrt/c:pjrt_c_api_cpu_plugin.so
        shell: cmd
