on:
  push:
    branches: [main, master]
  pull_request:

name: Build PJRT

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    name: Build PJRT
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          git clone https://github.com/openxla/xla

      - run: |
          cd xla
          bazel build //xla/pjrt/c:pjrt_c_api_cpu_plugin.so
