on:
  push:
    branches: [main, master]
  pull_request:

name: Build PJRT

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    name: Build PJRT
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          git clone https://github.com/openxla/xla
          cd xla
          git checkout 6319f0d

      - run: |
          choco install llvm
          which clang
          clang --version

      - run: |
          cd xla
          python configure.py --backend=cpu --os=windows --host_compiler=clang --clang_path=$(which clang)
          ls 

      - run: |
          cat xla_configure.bazelrc

      - run: |
          cd xla
          bazel build --compiler=clang-cl //xla/pjrt/c:pjrt_c_api_cpu_plugin.so
